version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: test-api
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: test-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
