export const REGISTER_WITHOUT_NAME_ERROR_MESSAGES = [
  'THE_EMAIL_SENDED_IS_INVALID',
  'EMAIL_SHOULD_NOT_BE_EMPTY',
  'EMAIL_SHOULD_BE_A_STRING',
  'PASSWORD_MUST_BE_AT_LEAST_4_CHARACTERS_HAVE_AN_UPPERCASE_LETTER_A_LOWERCASE_LETTER_A_NUMBER',
  'PASSWORD_MIN_LENGTH_IS_4',
  'PASSWORD_SHOULD_NOT_BE_EMPTY',
  'PASSWORD_SHOULD_BE_A_STRING',
  'PASSWORD_CONFIRMATION_SHOULD_NOT_BE_EMPTY',
  'PASSWORD_CONFIRMATION_SHOULD_BE_A_STRING'
];
